name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    # Weekly tests run by default:
    #   Scheduled workflows run on the latest commit on the default or base branch.
    #   (from https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)
    - cron: "0 0 * * 0"

jobs:
  test:
    # Run on 22.04 rather than latest to match my machine (as we install using --locked).
    # This avoids issues # with e.g. different gcc versions when building dm-tree from source
    # for Python 3.13.
    name: Test on ubuntu-22.04, py${{ matrix.python-version }}, ${{ matrix.env-type }}
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python-version: ["312", "313"]
        env-type: ["cpu", "base-cpu"]

    steps:
      - uses: actions/checkout@v6

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      - uses: prefix-dev/setup-pixi@v0.9.5
        with:
          pixi-version: v0.67.2
          cache: true
          environments: ${{ matrix.env-type }}-py${{ matrix.python-version }}

      - name: Lint
        run: |
          pixi run -e ${{ matrix.env-type }}-py${{ matrix.python-version }} lint

      - name: Type check
        run: |
          pixi run -e ${{ matrix.env-type }}-py${{ matrix.python-version }} type-check

      - name: Run tests
        run: |
          pixi run -e ${{ matrix.env-type }}-py${{ matrix.python-version }} test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v6
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
